"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { NewTaskDialogProvider, useNewTaskDialog } from "@/components/NewTaskDialogProvider";
import { TaskProvider } from "@/context/TaskContext";
import { SprintProvider } from "@/context/SprintContext";
import { SidebarProvider, useSidebar } from "@/context/SidebarContext";
import { MultiSelectProvider } from "@/context/MultiSelectContext";
import { useHotkeys } from "react-hotkeys-hook";
import { CommandPalette } from "@/components/CommandPalette";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/toaster";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata is not directly used in client components, but kept for reference
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function AppProviders({ children }: { children: React.ReactNode }) {
  const { openNewTaskDialog } = useNewTaskDialog();
  const { toggleSidebar, isCollapsed } = useSidebar();

  useHotkeys("mod+n", () => {
    openNewTaskDialog();
  });

  useHotkeys("mod+b", () => {
    toggleSidebar();
  });

  return (
    <TooltipProvider>
      <div className="min-h-screen bg-background">
        <Header />
        <div className="flex min-h-[calc(100vh-120px)]">
          <Sidebar />
          <main 
            className={`flex-1 p-8 bg-background transition-all duration-300 ${
              isCollapsed ? 'ml-0' : ''
            }`}
          >
            {children}
          </main>
        </div>
        <CommandPalette />
        <Toaster />
      </div>
    </TooltipProvider>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <SprintProvider>
            <TaskProvider>
              <MultiSelectProvider>
                <SidebarProvider>
                  <NewTaskDialogProvider>
                    <AppProviders>{children}</AppProviders>
                  </NewTaskDialogProvider>
                </SidebarProvider>
              </MultiSelectProvider>
            </TaskProvider>
          </SprintProvider>
        </SessionProvider>
      </body>
    </html>
  );
}